# Generated by Django 3.1.5 on 2021-02-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('classes', models.IntegerField(choices=[(0, '学术学位'), (1, '专业学位')])),
            ],
        ),
    ]
