# Generated by Django 3.1.5 on 2021-02-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Majors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorsCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='majors',
            name='classes',
        ),
    ]
