# Generated by Django 3.1.5 on 2021-02-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Majors', '0003_majorscode_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorscode',
            name='code',
        ),
        migrations.AddField(
            model_name='majors',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
