# Generated by Django 3.1.5 on 2021-02-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Majors', '0004_auto_20210207_0840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MajorsCode',
        ),
        migrations.AddField(
            model_name='majors',
            name='classes',
            field=models.BooleanField(choices=[(0, '专业学位'), (1, '学术学位')], default=1),
            preserve_default=False,
        ),
    ]
