# Generated by Django 3.1.5 on 2021-02-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Majors', '0005_auto_20210207_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majors',
            name='classes',
            field=models.IntegerField(choices=[(0, '专业学位'), (1, '学术学位')]),
        ),
    ]
