# Generated by Django 3.1.5 on 2021-02-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Majors', '0007_auto_20210207_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majors',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
