# Generated by Django 3.1.5 on 2021-02-05 12:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Majors', '0001_initial'),
        ('Colleges', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMajors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2021, 2, 5, 12, 14, 1, 286519, tzinfo=utc))),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Majors.majors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite major',
                'verbose_name_plural': 'Favorite majors',
            },
        ),
        migrations.CreateModel(
            name='FavoriteColleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2021, 2, 5, 12, 14, 1, 285994, tzinfo=utc))),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Colleges.colleges')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite College',
                'verbose_name_plural': 'Favorite Colleges',
            },
        ),
    ]
