# Generated by Django 3.1.5 on 2021-02-01 09:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Majors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteColleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2021, 2, 1, 9, 48, 35, 309896, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteMajors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2021, 2, 1, 9, 48, 35, 310373, tzinfo=utc))),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Majors.majors')),
            ],
        ),
    ]
