# Generated by Django 3.1.5 on 2021-02-07 14:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Colleges', '0001_initial'),
        ('Favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritecolleges',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 14, 16, 29, 417040, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='favoritecolleges',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='Colleges.colleges'),
        ),
        migrations.AlterField(
            model_name='favoritecolleges',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoritemajors',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 14, 16, 29, 417595, tzinfo=utc)),
        ),
    ]
