# Generated by Django 3.1.5 on 2021-02-07 14:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Favorites', '0002_auto_20210207_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritecolleges',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 14, 27, 2, 53748, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='favoritemajors',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 14, 27, 2, 54696, tzinfo=utc)),
        ),
    ]
