# Generated by Django 3.1.5 on 2021-02-08 09:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Majors', '0008_auto_20210207_0950'),
        ('Favorites', '0005_auto_20210208_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritecolleges',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 9, 45, 53, 702389, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='favoritemajors',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 9, 45, 53, 703109, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='favoritemajors',
            unique_together={('base',)},
        ),
    ]
