# Generated by Django 3.1.5 on 2021-02-08 09:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Colleges', '0001_initial'),
        ('Favorites', '0006_auto_20210208_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritecolleges',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 9, 47, 19, 45280, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='favoritemajors',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 9, 47, 19, 46010, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='favoritecolleges',
            unique_together={('base',)},
        ),
    ]
